Export merge function
RyuuGan/sol-merger pull request #11
Opened 2019-05-14 00:29 UTC by vinceau

Sometimes you just need the flattened source code as a string and not written to a file. This PR exports a `merge` function to be imported within node. The flattened source code as a string is returned.

2019-05-14 06:19 UTC, RyuuGan requested changes
Since merge is just a helper function we should also export `Merger` itself. 

Can you also add tests to `merge` function, like it is done at the second test:

https://github.com/RyuuGan/sol-merger/blob/master/test/index.js#L15

2019-05-14 06:19 UTC, RyuuGan commented on index.js
> +let merge = (file) => {
This function can be simplified:

```suggestion
const merge = async (file) => {
  const merger = new Merger({ delimeter: '\n\n' });
  return merger.processFile(file, true);
}
```

2019-05-14 06:19 UTC, RyuuGan commented on index.js
> +module.exports = merge;
We should also export `Merger` then if you need some more options to set up.

```suggestion
module.exports.Merger = Merger;
module.exports.merge = merge;
```

2019-05-14 06:19 UTC, RyuuGan commented on README.md
> +const merge = require('sol-merger');
This has to be changed due to last exports:

```suggestion
const { merge } = require('sol-merger');
```

2019-05-14 23:39 UTC, vinceau commented
The requested changes have been made and a test has been added for `merge`.

2019-05-15 05:49 UTC, RyuuGan approved these changes

2019-05-15 05:52 UTC, merged

2019-05-15 07:28 UTC, RyuuGan commented
Merged and published. Available since version `0.1.4`.